services:
  microserviceprojet:
    image: microserviceprojet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"

  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - microserviceprojet
